### ISSUE TITLE
Notebook #2: Issue getting data from thredds server

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/ACCESS-Visualisation-Recipes#1]
```python
thredds_server = "https://thredds.nci.org.au/thredds/dodsC/fs38/publications/"

#Temp at surf
ver = "CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/"
fpath = "r10i1p1f1/day/tas/gn/latest/tas_day_ACCESS-ESM1-5_historical_r10i1p1f1_gn_20000101-20141231.nc"
var = 'tas'
url = f"{thredds_server}{ver}{fpath}"

print(f'{url}.html')

ds = xr.open_dataset(url)
```

returns:

```OSError: [Errno -68] NetCDF: I/O failure: 'https://thredds.nci.org.au/thredds/dodsC/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r10i1p1f1/day/tas/gn/latest/tas_day_ACCESS-ESM1-5_historical_r10i1p1f1_gn_20000101-20141231.nc'``

direct download:

```
Error {
    code = 400;
    message = "Unrecognized request";
};
```

**Comment by OKaluza** [comment]
https://thredds.nci.org.au/thredds/dodsC/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r10i1p1f1/day/tas/gn/latest/tas_day_ACCESS-ESM1-5_historical_r10i1p1f1_gn_20000101-20141231.nc.html
This looks fine to me and above code runs, perhaps it was down when you tried??

**Comment by rbeucher** [comment]
Yes, it works fine for me now.
